import * as dotenv from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";
import fs from "node:fs";
import crypto from "node:crypto";

// Load .env from repo root regardless of cwd (npm run dev -w apps/gateway sets cwd to apps/gateway)
let loadedEnvPath: string | null = null;
try {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  const candidates = [
    path.resolve(".env"),
    path.resolve(path.join(process.cwd(), ".env")),
    path.resolve(path.join(__dirname, "../../../.env")),
    path.resolve(path.join(__dirname, "../../.env")),
    path.resolve("/app/.env"),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) {
      dotenv.config({ path: p });
      loadedEnvPath = p;
      break;
    }
  }
  // Fallback to default dotenv (cwd)
  if (!process.env.MASTER_KEY) dotenv.config();
} catch {
  dotenv.config();
}

function isPlaceholderMaster(v: string | undefined): boolean {
  if (!v) return true;
  return v.includes("change-me") || v === "fgk-master-dev-key" || v.trim().length < 16;
}
function isPlaceholderEncryption(v: string | undefined): boolean {
  if (!v) return true;
  const hex = v.replace(/[^0-9a-f]/gi, "");
  return hex.length < 64 || v.includes("0123456789abcdef0123456789abcdef");
}
function tryLoadPersistedFallback(): void {
  // If .env missing (Docker without env_file), reuse keys from data/.gateway-keys.json
  if (!isPlaceholderMaster(process.env.MASTER_KEY) && !isPlaceholderEncryption(process.env.ENCRYPTION_KEY)) return;
  const candidates = [
    path.resolve("data/.gateway-keys.json"),
    path.resolve(path.join(process.cwd(), "data/.gateway-keys.json")),
    path.resolve("/app/data/.gateway-keys.json"),
  ];
  try {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = path.dirname(__filename);
    candidates.unshift(path.resolve(path.join(__dirname, "../../../data/.gateway-keys.json")));
    candidates.unshift(path.resolve(path.join(__dirname, "../../data/.gateway-keys.json")));
  } catch {}
  for (const p of candidates) {
    try {
      if (fs.existsSync(p)) {
        const j = JSON.parse(fs.readFileSync(p, "utf-8"));
        if (isPlaceholderMaster(process.env.MASTER_KEY) && j.MASTER_KEY) process.env.MASTER_KEY = j.MASTER_KEY;
        if (isPlaceholderEncryption(process.env.ENCRYPTION_KEY) && j.ENCRYPTION_KEY) process.env.ENCRYPTION_KEY = j.ENCRYPTION_KEY;
        if (!isPlaceholderMaster(process.env.MASTER_KEY) || !isPlaceholderEncryption(process.env.ENCRYPTION_KEY)) {
          console.log(`[config] Restored keys from ${p}`);
          break;
        }
      }
    } catch {}
  }
}
function ensureKeysAutoGenerated() {
  let changed = false;
  if (isPlaceholderMaster(process.env.MASTER_KEY)) {
    const gen = `fgk-master-${crypto.randomBytes(16).toString("hex")}`;
    process.env.MASTER_KEY = gen;
    changed = true;
    console.log(`[config] Auto-generated MASTER_KEY=${gen} (no valid .env value found)`);
  }
  if (isPlaceholderEncryption(process.env.ENCRYPTION_KEY)) {
    const gen = crypto.randomBytes(32).toString("hex");
    process.env.ENCRYPTION_KEY = gen;
    changed = true;
    console.log(`[config] Auto-generated ENCRYPTION_KEY=${gen.slice(0, 8)}... (no valid .env value found)`);
  }
  if (changed && loadedEnvPath) {
    try {
      let content = fs.readFileSync(loadedEnvPath, "utf-8");
      if (process.env.MASTER_KEY) {
        if (content.includes("MASTER_KEY=")) content = content.replace(/^MASTER_KEY=.*$/m, `MASTER_KEY=${process.env.MASTER_KEY}`);
        else content += `\nMASTER_KEY=${process.env.MASTER_KEY}\n`;
      }
      if (process.env.ENCRYPTION_KEY) {
        if (content.includes("ENCRYPTION_KEY=")) content = content.replace(/^ENCRYPTION_KEY=.*$/m, `ENCRYPTION_KEY=${process.env.ENCRYPTION_KEY}`);
        else content += `\nENCRYPTION_KEY=${process.env.ENCRYPTION_KEY}\n`;
      }
      fs.writeFileSync(loadedEnvPath, content);
      console.log(`[config] Persisted auto-generated keys to ${loadedEnvPath}`);
    } catch (e) {
      console.warn(`[config] Could not persist auto-generated keys to ${loadedEnvPath}:`, (e as Error).message);
    }
  } else if (changed) {
    // No .env file found (e.g. Docker without env_file) — persist to data dir for next restart
    try {
      const dataDir = loadedEnvPath ? path.dirname(loadedEnvPath) : path.resolve("data");
      const persistPath = path.join(dataDir, ".gateway-keys.json");
      // also try /app/data
      const candidates = [persistPath, "/app/data/.gateway-keys.json", path.resolve(process.cwd(), "data/.gateway-keys.json")];
      const target = candidates[0];
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, JSON.stringify({ MASTER_KEY: process.env.MASTER_KEY, ENCRYPTION_KEY: process.env.ENCRYPTION_KEY }, null, 2));
      console.log(`[config] Persisted auto-generated keys to ${target} (fallback, no .env found)`);
    } catch {}
  }
}
tryLoadPersistedFallback();
ensureKeysAutoGenerated();

function parseTiers(): string[][] {
  try {
    const raw = process.env.FALLBACK_TIERS;
    if (!raw)
      return [
        ["nvidia-nim", "groq", "cerebras", "google-gemini"],
        ["cloudflare-workers-ai", "cohere", "sambanova", "siliconflow"],
        ["ovhcloud-ai-endpoints", "modelscope", "llm7-io", "hugging-face"],
        ["openrouter", "kilo-code", "pollinations", "orcarouter", "freeai", "cline"],
        ["anthropic", "claude-code", "codex", "agnes-ai"],
      ];
    return JSON.parse(raw);
  } catch {
    return [
      ["nvidia-nim", "groq", "cerebras", "google-gemini"],
      ["cloudflare-workers-ai", "cohere", "sambanova", "siliconflow"],
      ["ovhcloud-ai-endpoints", "modelscope", "llm7-io", "hugging-face"],
      ["openrouter", "kilo-code", "pollinations", "orcarouter", "freeai", "cline"],
      ["anthropic", "claude-code", "codex", "agnes-ai"],
    ];
  }
}

function parseKeys(env: string | undefined): string[] {
  if (!env) return [];
  return env.split(",").map((s) => s.trim()).filter(Boolean);
}

export const config = {
  port: parseInt(process.env.PORT || "7373", 10),
  nodeEnv: process.env.NODE_ENV || "development",
  logLevel: process.env.LOG_LEVEL || "info",
  corsOrigin: process.env.CORS_ORIGIN || "*",
  databaseUrl: process.env.DATABASE_URL || "file:./data.db",
  redisUrl: process.env.REDIS_URL || "",
  masterKey: process.env.MASTER_KEY || "fgk-master-dev-key",
  encryptionKey: process.env.ENCRYPTION_KEY || "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
  defaultModel: process.env.DEFAULT_MODEL || "auto",
  fallbackTiers: parseTiers(),
  circuitBreakerThreshold: parseInt(process.env.CIRCUIT_BREAKER_THRESHOLD || "5", 10),
  circuitBreakerCooldownMs: parseInt(process.env.CIRCUIT_BREAKER_COOLDOWN_MS || "30000", 10),
  // Vector 2 flags
  semanticCacheEnabled: process.env.SEMANTIC_CACHE_ENABLED === "1" || process.env.SEMANTIC_CACHE_ENABLED === "true",
  semanticCacheThreshold: parseFloat(process.env.SEMANTIC_THRESHOLD || "0.92"),
  semanticCacheTtlSec: parseInt(process.env.CACHE_TTL_S || "3600", 10),
  embeddingModel: (process.env.EMBEDDING_MODEL || "cohere/embed-english-v3.0").split(",")[0].trim(),
  embeddingModels: (process.env.EMBEDDING_MODEL || "cohere/embed-english-v3.0").split(",").map((s) => s.trim()).filter(Boolean),
  embeddingFallbacks: (process.env.EMBEDDING_FALLBACKS || "nvidia-nim/nvidia/nv-embed-v1,cloudflare-workers-ai/@cf/baai/bge-large-en-v1.5").split(",").map((s) => s.trim()).filter(Boolean),
  compressionEnabled: process.env.COMPRESSION_ENABLED === "1" || process.env.COMPRESSION_ENABLED === "true",
  costRoutingEnabled: process.env.COST_ROUTING_ENABLED === "1" || process.env.COST_ROUTING_ENABLED === "true",
  analyticsRetentionDays: parseInt(process.env.ANALYTICS_RETENTION_DAYS || "30", 10),
  providerKeys: {
    // freellms ids use hyphen, config keys use same slug
    "nvidia-nim": parseKeys(process.env.NVIDIA_API_KEYS),
    openrouter: parseKeys(process.env.OPENROUTER_API_KEYS),
    groq: parseKeys(process.env.GROQ_API_KEYS),
    "ollama-cloud": parseKeys(process.env.OLLAMA_CLOUD_API_KEYS),
    "kilo-code": parseKeys(process.env.KILO_CODE_API_KEYS),
    "github-models": parseKeys(process.env.GITHUB_TOKENS),
    cerebras: parseKeys(process.env.CEREBRAS_API_KEYS),
    "ovhcloud-ai-endpoints": parseKeys(process.env.OVHCLOUD_API_KEYS || process.env.OVH_AI_API_KEYS),
    "google-gemini": parseKeys(process.env.GEMINI_API_KEYS),
    gemini: parseKeys(process.env.GEMINI_API_KEYS), // alias
    "cloudflare-workers-ai": parseKeys(process.env.CLOUDFLARE_API_TOKEN),
    "llm7-io": parseKeys(process.env.LLM7_API_KEYS),
    modelscope: parseKeys(process.env.MODELSCOPE_API_KEYS),
    "chutes-ai": parseKeys(process.env.CHUTES_API_KEYS),
    chutes: parseKeys(process.env.CHUTES_API_KEYS), // alias
    "z-ai-zhipu-ai": parseKeys(process.env.Z_AI_API_KEYS),
    "agnes-ai": parseKeys(process.env.AGNES_API_KEYS),
    "mistral-ai": parseKeys(process.env.MISTRAL_API_KEYS),
    mistral: parseKeys(process.env.MISTRAL_API_KEYS),
    sambanova: parseKeys(process.env.SAMBANOVA_API_KEYS),
    cohere: parseKeys(process.env.COHERE_API_KEYS),
    "hugging-face": parseKeys(process.env.HUGGINGFACE_API_KEYS),
    huggingface: parseKeys(process.env.HUGGINGFACE_API_KEYS),
    "grok-xai": parseKeys(process.env.GROK_API_KEYS || process.env.XAI_API_KEYS),
    siliconflow: parseKeys(process.env.SILICONFLOW_API_KEYS),
    "aion-labs": parseKeys(process.env.AION_API_KEYS),
    opencode: parseKeys(process.env.OPENCODE_API_KEYS),
    deepseek: parseKeys(process.env.DEEPSEEK_API_KEYS),
    "alibaba-cloud-model-studio": parseKeys(process.env.ALIBABA_API_KEYS),
    nscale: parseKeys(process.env.NSCALE_API_KEYS),
    nebius: parseKeys(process.env.NEBIUS_API_KEYS),
    "ai21-labs": parseKeys(process.env.AI21_API_KEYS),
    // custom from opencode.json (user)
    orcarouter: parseKeys(process.env.ORCAROUTER_API_KEYS),
    freeai: parseKeys(process.env.FREEAI_API_KEYS),
    cline: parseKeys(process.env.CLINE_API_KEYS),
    anthropic: parseKeys(process.env.ANTHROPIC_API_KEYS || process.env.CLAUDE_API_KEYS),
    "claude-code": parseKeys(process.env.CLAUDE_CODE_API_KEYS || process.env.ANTHROPIC_API_KEYS || process.env.CLAUDE_API_KEYS),
    codex: parseKeys(process.env.CODEX_API_KEYS || process.env.OPENAI_API_KEYS),
    // legacy / scraped
    nvidia: parseKeys(process.env.NVIDIA_API_KEYS),
    together: parseKeys(process.env.TOGETHER_API_KEYS),
    fireworks: parseKeys(process.env.FIREWORKS_API_KEYS),
    novita: parseKeys(process.env.NOVITA_API_KEYS),
    pollinations: parseKeys(process.env.POLLINATIONS_API_KEY),
  } as Record<string, string[]>,
};

export const isPostgres = config.databaseUrl.startsWith("postgres");
