// Direct console URLs for obtaining API keys (from freellms.org Get API Key buttons + opencode config)
export const getKeyUrls: Record<string, string> = {
  "nvidia-nim": "https://build.nvidia.com/settings/api-keys",
  groq: "https://console.groq.com/keys",
  cerebras: "https://cloud.cerebras.ai/",
  openrouter: "https://openrouter.ai/keys",
  "google-gemini": "https://aistudio.google.com/app/apikey",
  gemini: "https://aistudio.google.com/app/apikey",
  "github-models": "https://github.com/settings/tokens",
  "ovhcloud-ai-endpoints": "https://console.ovh.com",
  cohere: "https://dashboard.cohere.com/api-keys",
  "mistral-ai": "https://console.mistral.ai/api-keys",
  mistral: "https://console.mistral.ai/api-keys",
  modelscope: "https://modelscope.cn/my/myaccesstoken",
  "cloudflare-workers-ai": "https://dash.cloudflare.com/",
  "llm7-io": "https://api.llm7.io",
  "chutes-ai": "https://chutes.ai",
  chutes: "https://chutes.ai",
  sambanova: "https://cloud.sambanova.ai/apis",
  siliconflow: "https://cloud.siliconflow.cn/account/ak",
  "glhf-chat": "https://glhf.chat",
  glhf: "https://glhf.chat",
  "kilo-code": "https://kilocode.ai",
  opencode: "https://opencode.ai",
  "agnes-ai": "https://agnes-ai.com",
  "aion-labs": "https://aionlabs.ai",
  "z-ai-zhipu-ai": "https://open.bigmodel.cn/usercenter/proj-mgmt/apikeys",
  experientiallabs: "https://platform.experientiallabs.ai",
  experiential: "https://platform.experientiallabs.ai",
  "experiential-cloud": "https://platform.experientiallabs.ai",
  experiential_cloud: "https://platform.experientiallabs.ai",
  kiraai: "https://kiraai.vn",
  kira: "https://kiraai.vn",
  "grok-xai": "https://console.x.ai/",
  xai: "https://console.x.ai/",
  deepseek: "https://platform.deepseek.com/api_keys",
  "alibaba-cloud-model-studio": "https://dashscope.console.aliyun.com/apiKey",
  nscale: "https://nscale.com",
  nebius: "https://studio.nebius.com",
  "ai21-labs": "https://studio.ai21.com/account/api-key",
  together: "https://api.together.xyz/settings/api-keys",
  fireworks: "https://fireworks.ai/api-keys",
  novita: "https://novita.ai/settings/key",
  pollinations: "https://enter.pollinations.ai",
  "ollama-cloud": "https://ollama.com/settings/keys",
  orcarouter: "https://api.orcarouter.ai",
  freeai: "https://api.free.ai",
  cline: "https://api.cline.bot",
  anthropic: "https://console.anthropic.com/settings/keys",
  "claude-code": "https://console.anthropic.com/settings/keys",
  codex: "https://platform.openai.com/api-keys",
};

export function getKeyUrl(slug: string): string {
  return getKeyUrls[slug] || `https://freellms.org/providers/${slug}`;
}
